### PR TITLE
IFU-rocm6.0_internal_testing-2023-09-08

### PR DESCRIPTION
**Pull request by pruthvistony**
Please refer CP file
- https://amdcloud-my.sharepoint.com/:x:/r/personal/pmagundu_amd_com/_layouts/15/doc2.aspx?sourcedoc=%7B2c1b2bbc-6f31-4cc3-8e97-be74d273821d%7D&action=edit&activeCell=%27Sheet2%27!B2&wdinitialsession=d09fc073-a2ae-42e8-b4e3-30674e8bc192&wdrldsc=21&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT

Sheet - CP_internal_testing_branch

Confluence page for new IFU process - https://confluence.amd.com/pages/viewpage.action?pageId=875512877

### CODE REVIEW

**Comment by pruthvistony** [comment]
To be upstreamed, task list
gloo - https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5721
kineto - https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/5722

**Comment by pruthvistony** [comment]
Builds on ROCm 5.6 rel
IFU_Base_sep08 - http://rocm-ci.amd.com/view/Release-5.6/job/framework-pytorch-ci_rel-5.6/78/
IFU_CP_sep08 - http://rocm-ci.amd.com/view/Release-5.6/job/framework-pytorch-ci_rel-5.6/83/

Builds on ROCm mainline 12755
IFU_CP_sep08 - http://rocm-ci.amd.com/job/mainline-framework-pytorch-ci/1329/

**Comment by pruthvistony** [comment]
hipblasLT is disabled due to conflicts with latest hipblasLT changes.

**Comment by jithunnair-amd** [comment]
> hipblasLT is disabled due to conflicts with latest hipblasLT changes.

@pruthvistony Please mention some more details of the conflicts for reference.

**Comment by pruthvistony** [comment]
> > hipblasLT is disabled due to conflicts with latest hipblasLT changes.
> 
> @pruthvistony Please mention some more details of the conflicts for reference.

Error extract
```
[2023-09-14T20:41:10.578Z] /var/lib/jenkins/pytorch/aten/src/ATen/hip/HIPBlas.cpp: In function ‘void at::cuda::blas::dot(hipblasHandle_t, int, const Dtype*, int, const Dtype*, int, Dtype*) [with Dtype = c10::Half; hipblasHandle_t = void*]’:
[2023-09-14T20:41:10.578Z] /var/lib/jenkins/pytorch/aten/src/ATen/hip/HIPBlas.cpp:1439:16: error: cannot convert ‘hipblasltDatatype_t’ to ‘hipblasDatatype_t’ for argument ‘4’ to ‘hipblasStatus_t hipblasDotEx(hipblasHandle_t, int, const void*, hipblasDatatype_t, int, const void*, hipblasDatatype_t, int, void*, hipblasDatatype_t, hipblasDatatype_t)’
[2023-09-14T20:41:10.578Z]        HIP_R_32F));
[2023-09-14T20:41:10.578Z]                 ^
```
hipblasLT commit which added new data type - https://github.com/ROCmSoftwarePlatform/hipBLASLt/commit
/ba869b725ba45d901204023d8aedb5d1c39bffbf

Discussed with @jeffdaily  and got to know more details about the hipBLASLt integration which is breaking. Have sent a mail to concerned teams which needs to be fixed.

@jeffdaily, Thanks for your inputs.

**Comment by pruthvistony** [comment]
Based on the recent upstream updates, `.pytorch-test-times.json` will be downloaded a build time in `build.sh`
```
if [[ "$BUILD_ENVIRONMENT" != *libtorch* && "$BUILD_ENVIRONMENT" != *bazel* ]]; then
  # export test times so that potential sharded tests that'll branch off this build will use consistent data
  # don't do this for libtorch as libtorch is C++ only and thus won't have python tests run on its build
  python tools/stats/export_test_times.py
fi
```

We have currently added this file as part of `IFU_base_sep08` branch in the commit - https://github.com/ROCmSoftwarePlatform/pytorch/commit/4c540edbb91f75d7a9571cc05114051eeccf0fcc

This needs to be reverted and few updates for current `BUILD_ENVIRONMENT` env. All these changes I believe shouldnt be part of this IFU and will done as a separate commit to rocm6.0_internal_testing branch.

**Comment by pruthvistony** [comment]
Test reports single GPU 
run1 - 
[ifu_pyt_test_3.log.zip](https://github.com/ROCmSoftwarePlatform/pytorch/files/12666737/ifu_pyt_test_3.log.zip)
run 2 with sharding enabled - 
[ifu_pyt_test_with_shards_4.log.zip](https://github.com/ROCmSoftwarePlatform/pytorch/files/12666764/ifu_pyt_test_with_shards_4.log.zip)

**Comment by pruthvistony** [comment]
Distributed test runs
shard 1 - 
[ifu_pyt_test_with_shards_1_dist_6.log.zip](https://github.com/ROCmSoftwarePlatform/pytorch/files/12668929/ifu_pyt_test_with_shards_1_dist_6.log.zip)
Shard 2 - 
[ifu_pyt_test_with_shards_2_dist_7.log.zip](https://github.com/ROCmSoftwarePlatform/pytorch/files/12668930/ifu_pyt_test_with_shards_2_dist_7.log.zip)

**Comment by pruthvistony** [comment]
Added - https://gerrit-git.amd.com/c/compute/ec/ml-framework-ci/+/928372

**Review by jithunnair-amd — APPROVED** [review]

**Comment by pruthvistony** [comment]
> Added - https://gerrit-git.amd.com/c/compute/ec/ml-framework-ci/+/928372

Had a discussion on this, we want to refer to the `[default]` key in the test-times files, so above changes to refer to `[rocm-build_environment]` key is NOT required for now.

**Comment by jithunnair-amd** [comment]
> Based on the recent upstream updates, `.pytorch-test-times.json` will be downloaded at build time in `build.sh`
> 
> ```
> if [[ "$BUILD_ENVIRONMENT" != *libtorch* && "$BUILD_ENVIRONMENT" != *bazel* ]]; then
>   # export test times so that potential sharded tests that'll branch off this build will use consistent data
>   # don't do this for libtorch as libtorch is C++ only and thus won't have python tests run on its build
>   python tools/stats/export_test_times.py
> fi
> ```
> 
> We have currently added this file as part of `IFU_base_sep08` branch in the commit - [4c540ed](https://github.com/ROCmSoftwarePlatform/pytorch/commit/4c540edbb91f75d7a9571cc05114051eeccf0fcc) if the file is present the above download logic is skipped.
> 
> This needs to be reverted and few updates for current `BUILD_ENVIRONMENT` env. All these changes I believe shouldnt be part of this IFU and will done into the DEVOps scripts.

As per discussion offline, we will add a snapshot version of the json file in this branch, and the test-infra code will use the "default" build config because it might not match the BUILD_ENVIRONMENT set in QA testing. We will update the json file entries as and when necessary to ensure optimal sharding based on runtimes seen by QA.

**Comment by pruthvistony** [comment]
UT failure report - https://amdcloud-my.sharepoint.com/:x:/r/personal/pmagundu_amd_com/_layouts/15/Doc.aspx?sourcedoc=%7B83fd7ab3-2e79-4f6b-8dcb-9eccad39d68c%7D&action=editnew
