### PR TITLE
[SOW MS3] Revert workaround for SWDEV-344283

### PR DESCRIPTION
**Pull request by alugorey**
hipSolver const bug was fixed as of rocm build 10604. This PR reverts the workaround for that bug.

python test/test_linalg.py
```
----------------------------------------------------------------------
Ran 1494 tests in 550.543s

OK (skipped=105)
```

### CODE REVIEW

**Comment by alugorey** [comment]
Docker container used for testing: compute-artifactory.amd.com:5000/rocm-plus-docker/framework/compute-rocm-dkms-no-npi-
hipclang:10619_ubuntu20.04_py3.7_pytorch_rocm5.3_internal_testing_964735b

File: aten/src/ATen/native/cuda/linalg/CUDASolver.h [hunk 1]
```diff
@@ -9,13 +9,6 @@
 
 #if defined(CUDART_VERSION) || defined(ROCM_VERSION) && ROCM_VERSION >= 50200
 
-#ifdef CUDART_VERSION
-#define CONST_QUALIFIER const
-#else
-// hipSOLVER functions in current ROCM (5.2) miss CONST_QUALIFIER qualifiers
-#define CONST_QUALIFIER
```
Comment (jithunnair-amd) [inline aten/src/ATen/native/cuda/linalg/CUDASolver.h:16]: @alugorey Actually, this PR shouldn't have been merged, because it breaks PyTorch build on ROCm5.2: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-build/283/consoleText
```
Aug 20 06:53:23 /var/lib/jenkins/pytorch/aten/src/ATen/native/hip/linalg/HIPSolver.cpp:789:65: error: invalid conversion from ‘const float*’ to ‘float*’ [-fpermissive]
Aug 20 06:53:23   789 |   TORCH_CUSOLVER_CHECK(hipsolverDnSpotrs(handle, uplo, n, nrhs, A, lda, B, ldb, devInfo));
Aug 20 06:53:23       |                                                                 ^
Aug 20 06:53:23       |                                                                 |
Aug 20 06:53:23       |                                                                 const float*
```

**Comment by jithunnair-amd** [comment]
@alugorey In fact, the CI run for this PR also showed that it breaks PyTorch build for ROCm5.2. Sorry for overlooking that. I'm going to revert this change and you can submit another PR to conditionalize the additional of the const based on ROCm version.

**Comment by HaiShaw** [comment]
This revert only works for ROCm5.3 and would break ROCm5.2
